x-restart-policy: &restart_policy
  restart: always

x-backend: &backend_config
  <<: *restart_policy
  user: docker
  build:
    context: .backend
    dockerfile: Dockerfile
  working_dir: ${PWD}
  volumes:
    - .:${PWD}
    - .backend/home/.nuget:/home/docker/.nuget
    - .backend/home/.aspnet:/home/docker/.aspnet
    - .backend/home/.dotnet:/home/docker/.dotnet
  stdin_open: true
  tty: true
  environment:
    ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
    ASPNETCORE_Kestrel__Certificates__Default__Path: /home/docker/.aspnet/https/cert.pfx

x-database: &db_config
  <<: *restart_policy
  image: mcr.microsoft.com/mssql/server:2022-latest
  environment:
    ACCEPT_EULA: Y
    MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-Secret!123}
  expose:
    - 1433
  healthcheck:
    test:
      - "CMD-SHELL"
      - "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q 'SELECT 1' || exit 1"
    start_period: 10s
    interval: 5s
    timeout: 5s
    retries: 5

services:
  backend:
    <<: *backend_config
    ports:
      - "${API_HTTP_PORT:-5000}:5000"
      - "${API_HTTPS_PORT:-5001}:5001"

  database:
    <<: *db_config
    volumes:
      - videoGameDB:/var/opt/mssql:rw

  database_for_testing:
    <<: *db_config
    user: root
    tmpfs:
      - /var/opt/mssql/data:rw

  adminer:
    <<: *restart_policy
    image: adminer:4.8.1
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    environment:
      ADMINER_DESIGN: dark
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DEFAULT_PORT: 1433
      ADMINER_DEFAULT_USER: sa
      ADMINER_DEFAULT_PASSWORD: ${MSSQL_SA_PASSWORD:-Secret!123}

  sqlpad:
    <<: *restart_policy
    image: sqlpad/sqlpad
    ports:
      - "${SQLPAD_PORT:-3000}:3000"
    environment:
      SQLPAD_ADMIN: ${SQLPAD_ADMIN:-admin@sqlpad.com}
      SQLPAD_ADMIN_PASSWORD: ${SQLPAD_ADMIN_PASSWORD:-secret}

volumes:
  videoGameDB:
    driver: local
